Homework-#9, Tallinn-Delivery API tests are added.
Dmytro-Mykhailenko/password-checker pull request #2
Opened 2024-02-26 20:52 UTC by Dmytro-Mykhailenko

Endpoints: "Get all orders", "Get an order by ID", "Delete an order by ID"

2024-03-04 18:31 UTC, vladimir-tl requested changes

2024-03-04 18:31 UTC, vladimir-tl commented on src/test/java/api/RestApiMockedTest.java
> +        for (int x: VALID_ID){
использовать тут циклы это не очень хорошая практика
мы умеем уже делать параметризацию

цикл нужно убрать

2024-03-05 05:58 UTC, Dmytro-Mykhailenko commented on src/test/java/api/RestApiMockedTest.java
> +        for (int x: VALID_ID){
уже переделал..

2024-03-10 11:02 UTC, vladimir-tl approved these changes

2024-03-10 15:27 UTC, merged